#Discord application/bot token
botToken=

#Guild id, or server identifiers for registering guild commands useful for quickly testing command changes
guildIds=

# local IP address of your pixoo display
pixooIp=

# Should commands be registered with discord on start, should be true for first run
publishSlashCommands=

# Use guild ids, over global commands, guild commands update much faster
useGuildIds=
